/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertError: typeof import('./components/UI/AlertError.vue')['default']
    CardAdd: typeof import('./components/UI/CardAdd.vue')['default']
    Cards: typeof import('./components/UI/Cards.vue')['default']
    DialogLoader: typeof import('./components/modals/DialogLoader.vue')['default']
    Modal: typeof import('./components/modals/Modal.vue')['default']
    ModalAdd: typeof import('./components/modals/services/ModalAdd.vue')['default']
    ModalAddVM: typeof import('./components/modals/VirtualMachines/ModalAddVM.vue')['default']
    ModalDelete: typeof import('./components/modals/ModalDelete.vue')['default']
    ModalEdit: typeof import('./components/modals/services/ModalEdit.vue')['default']
    ModalEditVM: typeof import('./components/modals/VirtualMachines/ModalEditVM.vue')['default']
    ModalInfo: typeof import('./components/modals/services/ModalInfo.vue')['default']
    ModalInfoVM: typeof import('./components/modals/VirtualMachines/ModalInfoVM.vue')['default']
    Navbar: typeof import('./components/navigation/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/navigation/SearchBar.vue')['default']
    SkeletonLoader: typeof import('./components/UI/SkeletonLoader.vue')['default']
    Snackbar: typeof import('./components/UI/Snackbar.vue')['default']
    TagAccordion: typeof import('./components/TagAccordion.vue')['default']
  }
}
